//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public int WorkerID { get; set; }
        public int ToolID { get; set; }
        public int Action { get; set; }
        public int Count { get; set; }
        public bool Readed { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
