//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DeletedTool> DeletedTools { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<ToolsUs> ToolsUses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WriteOffTool> WriteOffTools { get; set; }
    
        public virtual ObjectResult<Nullable<int>> DeleteExpiredSessions(Nullable<System.DateTime> dateOlder)
        {
            var dateOlderParameter = dateOlder.HasValue ?
                new ObjectParameter("DateOlder", dateOlder) :
                new ObjectParameter("DateOlder", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteExpiredSessions", dateOlderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DeleteUserSessionsByToken(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteUserSessionsByToken", tokenParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DeleteUserSessionsByUserID(Nullable<int> workerID)
        {
            var workerIDParameter = workerID.HasValue ?
                new ObjectParameter("WorkerID", workerID) :
                new ObjectParameter("WorkerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DeleteUserSessionsByUserID", workerIDParameter);
        }
    
        public virtual ObjectResult<Get_ToolsUsedByUser_Result> Get_ToolsUsedByUser(Nullable<int> workerID)
        {
            var workerIDParameter = workerID.HasValue ?
                new ObjectParameter("WorkerID", workerID) :
                new ObjectParameter("WorkerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ToolsUsedByUser_Result>("Get_ToolsUsedByUser", workerIDParameter);
        }
    
        public virtual ObjectResult<Get_UsersUsedTool_Result> Get_UsersUsedTool(Nullable<int> toolID)
        {
            var toolIDParameter = toolID.HasValue ?
                new ObjectParameter("ToolID", toolID) :
                new ObjectParameter("ToolID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_UsersUsedTool_Result>("Get_UsersUsedTool", toolIDParameter);
        }
    }
}
