//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int UserSessionID { get; set; }
        public int WorkerID { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime Expired { get; set; }
        public bool RememberMe { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
